name: Check Poetry Project

on:
  workflow_call:
    inputs:
      arm64:
        type: boolean
        default: false
      poetry-version:
        required: false
        default: "1.8.5"
        type: string

jobs:
  define-matrix:
    runs-on: ubuntu-slim

    permissions: {}

    outputs:
      platforms: ${{ steps.platforms.outputs.platforms }}

    steps:
      - id: platforms
        run: |
          echo platforms='${{
            inputs.arm64
            && '[{"key":"linux-amd64","os":"linux","architecture":"amd64","runner":"ubuntu-24.04"},{"key":"linux-arm64","os":"linux","architecture":"arm64","runner":"ubuntu-24.04-arm"}]'
            || '[{"key":"linux-amd64","os":"linux","architecture":"amd64","runner":"ubuntu-24.04"}]'
          }}' >> "$GITHUB_OUTPUT"


  test:
    needs:
      - define-matrix

    strategy:
      matrix:
        platform: ${{ fromJSON(needs.define-matrix.outputs.platforms) }}

    permissions:
      contents: read

    runs-on: ${{ matrix.platform.runner }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
      with:
        python-version-file: pyproject.toml
    - name: Install poetry
      run: pipx install "poetry==${{ inputs.poetry-version }}"
    - name: Check poetry.lock
      run: poetry check
    - name: Install poetry env from pyproject.toml
      run: poetry install
    - name: Run tests
      run: poetry run pytest
    - name: Check lint rules
      run: poetry run flake8
    - name: Check code style
      run: poetry run black --check .
    - name: Check type annotations
      run: poetry run mypy .
