name: Maven Deploy

on:
  workflow_call:
    inputs:
      time-zone:
        required: false
        default: "Europe/Amsterdam"
        type: string
      timeout-minutes:
        required: false
        default: 10
        type: number

jobs:
  maven-deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    env:
      TZ: ${{ inputs.time-zone }}
      MAVEN_ARGS: '--no-transfer-progress --color always'
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::917951871879:role/GitHubActionsBgOrg

      - name: Get CodeArtifact Authorization Token
        run: |
          codeartifact_auth_token=$(aws codeartifact  get-authorization-token --domain nisv-ateam --domain-owner 917951871879 --region eu-west-1 --query authorizationToken --output text)
          echo "::add-mask::$codeartifact_auth_token"
          echo "CODEARTIFACT_AUTH_TOKEN=$codeartifact_auth_token" >> "$GITHUB_ENV"

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Set Maven settings.xml
        run: echo "${{ vars.MAVEN_CODE_ARTIFACT_SETTINGS }}" | base64 --decode > ~/.m2/settings.xml

      - name: Maven Deploy
        run: |
          mvn clean deploy -B -U -V -fae -ntp -DskipTests|| { echo "Maven Deploy failed."; exit 1; }

      - name: Find all folders with Dockerfile
        run: |
          folders=$(find . -type f -name 'Dockerfile' -exec dirname {} \;)
          [ -z "$folders" ] && echo "No Dockerfiles found. Docker build will skip." && exit 0
          echo FOLDERS=$folders >> $GITHUB_ENV

      - name: ECR Login
        if: ${{ env.FOLDERS }}
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6

      - name: Log in to GHCR
        if: ${{ env.FOLDERS }}
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_PAT }}

      - name: Extract repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Generate a token
        if: ${{ env.FOLDERS }}
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf #v2.2.1
        with:
          app-id: ${{ vars.BG_APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: ${{ env.REPO_NAME }}, k8s-workloads

      - name: Build, push Docker images, and trigger workflows for auto deployment
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        if: ${{ env.FOLDERS }}
        run: |
          REPOSITORY="${{ github.event.repository.name }}"
          # convert to lowercase
          REPOSITORY="${REPOSITORY,,}"
          for dir in ${{ env.FOLDERS }}; do
            echo "Building Docker image in directory: $dir"
            FILE=$(find $dir/target -maxdepth 1 -type f \( -name "*.war" -o -name "*.jar" \))
            BUILD_TYPE=${FILE##*.}
            IMAGE_TAG=$(basename $FILE .$BUILD_TYPE)-$(echo ${{ github.sha }} | cut -c1-7)
            ECR_IMAGE_REPOSITORY=917951871879.dkr.ecr.eu-west-1.amazonaws.com/${REPOSITORY}

            docker build -t $ECR_IMAGE_REPOSITORY:$IMAGE_TAG $dir
            docker push $ECR_IMAGE_REPOSITORY:$IMAGE_TAG

            echo "Update image for deployment script of test environment"
            gh workflow run update-maven-projects-image-tag.yml \
            -r main \
            -R github.com/beeldengeluid/k8s-workloads \
            -f project=${REPOSITORY} \
            -f environments=tst \
            -f image_tag_prefix=$(basename $dir) \
            -f image_tag=$IMAGE_TAG
          done
                    
