name: Maven Deploy

on:
  workflow_call:
    inputs:
      time-zone:
        required: false
        default: "Europe/Amsterdam"
        type: string
      timeout-minutes:
        required: false
        default: 10
        type: number

jobs:
  maven-deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    env:
      TZ: ${{ inputs.time-zone }}
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::917951871879:role/GitHubActionsBgOrg
      - name: Get CodeArtifact Authorization Token
        run: |
          codeartifact_auth_token=$(aws codeartifact  get-authorization-token --domain nisv-ateam --domain-owner 917951871879 --region eu-west-1 --query authorizationToken --output text)
          echo "::add-mask::$codeartifact_auth_token"
          echo "CODEARTIFACT_AUTH_TOKEN=$codeartifact_auth_token" >> "$GITHUB_ENV"

      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'
          cache: 'maven'
      - name: Set Maven settings.xml # This seems, odd, setup-java can do this
        run: echo "${{ vars.MAVEN_CODE_ARTIFACT_SETTINGS }}" | base64 --decode > ~/.m2/settings.xml
      - name: Maven install
        run: |
          mvn -B -U clean install -fae
      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      - name: Build, push Docker images, and trigger workflows for auto deployment
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          ECR_IMAGE_REPOSITORY=917951871879.dkr.ecr.eu-west-1.amazonaws.com/${{ github.event.repository.name }}
          for dir in `find . -name docker -type d`; do
             cd $dir/../..
             ARTIFACTID=`mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout`
             VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
             IMAGE_TAG=$VERSION
             echo $IMAGE_TAG
             docker image ls
             docker image tag $ARTIFACTID:$IMAGE_TAG $ECR_IMAGE_REPOSITORY/$ARTIFACTID:$IMAGE_TAG
             docker image ls
             docker push $ECR_IMAGE_REPOSITORY/$ARTIFACTID:$IMAGE_TAG
          done
                    
