# .github/workflows/build-and-push-image.yml

name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      runner-label:
        required: true
        type: string
      artifact-url:
        description: 'The URL of the Artifact WAR file to be downloaded'
        required: true
        type: string

jobs:
  build-push-image:
    runs-on: ${{inputs.runner-label}}
    steps:
      - name: Get Metadata as env variables
        run: |
          echo "IMAGE_TAG=$(basename ${{ inputs.artifact-url }} | sed 's/\.[^.]*$//')-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Download Artifact WAR
        run: |
          curl -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" -f -o "ROOT.war" "${{ inputs.artifact-url }}"

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image
        run: |
          docker build -t 917951871879.dkr.ecr.eu-west-1.amazonaws.com/museum-api:${{ env.IMAGE_TAG }} \
          --build-arg BASE_IMAGE=${{ vars.BASE_IMAGE }} \
          --build-arg WAR_FILE_PATH="ROOT.war" .

      - name: Push Image to AWS ECR Repository
        run: |
          docker push "917951871879.dkr.ecr.eu-west-1.amazonaws.com/museum-api:${{ env.IMAGE_TAG }}"

      - name: Post Maven Clean
        run: mvn clean

      - name: Post Clean Docker Images
        run: |
          docker rmi 917951871879.dkr.ecr.eu-west-1.amazonaws.com/museum-api:${{ env.IMAGE_TAG }}
