# .github/workflows/build-and-push-image.yml

name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      artifact-url:
        description: 'The URL of the Artifact WAR file to be downloaded'
        required: true
        type: string
      codeartifact_auth_token:
        required: false
        type: string
      runner-label:
        required: false
        default: 'ubuntu-24.04'
        type: string
      maven-repository-profile:
        description: 'Maven repository profile ID'
        required: true
        default: code-artifact
        type: string

jobs:
  publish-image:
    runs-on: ${{ inputs.runner-label }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::917951871879:role/GitHubActionsBgOrg

      - name: Get Metadata as env variables
        run: |
          echo "IMAGE_TAG=$(basename ${{ inputs.artifact-url }} | sed 's/\.[^.]*$//')-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Download Artifact WAR
        run: |
          if [[ "${{ inputs.maven-repository-profile }}" == 'code-artifact' ]]; then
            AUTH_CREDENTIALS="aws:${{ inputs.codeartifact_auth_token }}"
          elif [[ "${{ inputs.maven-repository-profile }}" == 'beng-nexus' ]]; then
            AUTH_CREDENTIALS="${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}"
          else
            echo "Invalid Maven repository: ${{ inputs.maven-repository-profile }}" && exit 1
          fi
          
          curl -u "${AUTH_CREDENTIALS}" -f -L "${{ inputs.artifact-url }}" -o "ROOT.war" || { echo "Failed to download artifact."; exit 1; }

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 #v2.0.1

      - name: Build image
        run: |
          docker build -t 917951871879.dkr.ecr.eu-west-1.amazonaws.com/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }} --build-arg WAR_FILE_PATH="ROOT.war"  .

      - name: Push Image to AWS ECR Repository
        run: |
          docker push "917951871879.dkr.ecr.eu-west-1.amazonaws.com/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }}"
          
      
