name: Test(tst) env Deployment

on:
  workflow_call:
    inputs:
      time-zone:
        required: false
        default: "Europe/Amsterdam"
        type: string
      deployment-module:
        required: false
        type: string
      timeout-minutes:
        required: false
        default: 10
        type: number

jobs:
  maven-deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout-minutes }}
    env:
      TZ: ${{ inputs.time-zone }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
      MAVEN_ARGS: '-B -U -V -fae -DskipTests --no-transfer-progress'

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@f24d7193d98baebaeacc7e2227925dd47cc267f5 # v4.2.0
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::917951871879:role/GitHubActionsBgOrg

      - name: Get CodeArtifact Authorization Token
        run: |
          codeartifact_auth_token=$(aws codeartifact  get-authorization-token --domain nisv-ateam --domain-owner 917951871879 --region eu-west-1 --query authorizationToken --output text)
          echo "::add-mask::$codeartifact_auth_token"
          echo "CODEARTIFACT_AUTH_TOKEN=$codeartifact_auth_token" >> "$GITHUB_ENV"

      - name: Set up JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Set Maven settings.xml
        run: echo "${{ vars.MAVEN_CODE_ARTIFACT_SETTINGS }}" | base64 --decode > ~/.m2/settings.xml

      - name: Maven Deploy
        run: |
          mvn clean deploy || { echo "Maven Deploy failed."; exit 1; }

      - name: ECR Login
        if: ${{ inputs.deployment-module }}
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Prepare Docker image tag and repository
        if: ${{ inputs.deployment-module }}
        run: |
          FILE=$(find ${{ inputs.deployment-module }}/target -maxdepth 1 -type f \( -name "*.war" -o -name "*.jar" \))
          IMAGE_TAG=$(basename $FILE | sed 's/\.\(jar\|war\)$//')-$(echo ${{ github.sha }} | cut -c1-7)
          ECR_REPO=917951871879.dkr.ecr.eu-west-1.amazonaws.com/${{ github.event.repository.name }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "ECR_REPO=$ECR_REPO" >> $GITHUB_ENV

      - name: Build, push Docker images.

        run: |
          docker build -t ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}  ${{ inputs.deployment-module }}
          docker push ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }} 

      - name: Create and Push Release Branch
        run: |
          git checkout -b update-tst-deployment-image || git checkout update-tst-deployment-image
          git push origin update-tst-deployment-image -f

      - name: Update image in Kubernetes deployment
        if: ${{ inputs.deployment-module }}
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          git checkout -b update-tst-deployment-image || git checkout update-tst-deployment-image
          sed -i "s|newTag: .*|newTag: ${{ image_tag }}|" "/k8s/tst/kustomization.yml"
          git add /k8s/tst/kustomization.yml
          git commit -m "Update image tag to $IMAGE_TAG in project "/k8s/tst/kustomization.yml" -a
          git push origin update-tst-deployment-image -f

      - name: Create and Auto-Merge Pull Request
        run: |
          gh pr create --title "Update image tag to ${{ env.IMAGE_TAG }}" \
                      --body "This PR updates the image tag in the Kubernetes deployment files." \
                      --head ${{ github.head_ref }} \
                      --base ${{ github.event.repository.default_branch }}
          gh pr merge ${{ github.head_ref }} --merge --admin
          
          
          
                    
